"""Contract and real-PostgreSQL tests for explicit pre-ledger adoption."""

from __future__ import annotations

from contextlib import asynccontextmanager
from unittest.mock import patch

import asyncpg
import pytest

from bddk_mcp.cli import build_parser
from bddk_mcp.migrations import (
    LATEST_SCHEMA_VERSION,
    LegacyAdoptionError,
    MigrationError,
    MigrationPrerequisiteError,
    migrate,
)


class _PinnedPool:
    def __init__(self, connection) -> None:
        self.connection = connection

    @asynccontextmanager
    async def acquire(self):
        yield self.connection


def test_adoption_requires_an_explicit_cli_flag() -> None:
    parser = build_parser()

    ordinary = parser.parse_args(["migrate"])
    adoption = parser.parse_args(["migrate", "--adopt-legacy"])

    assert ordinary.adopt_legacy is False
    assert adoption.adopt_legacy is True


async def _remove_managed_history(connection) -> None:
    await connection.execute("DROP SCHEMA IF EXISTS bddk_operator CASCADE")
    await connection.execute("DROP SCHEMA IF EXISTS bddk_meta CASCADE")
    # Remove the additive v4 legal-curation pilot before reconstructing the
    # exact unmanaged v1 fixture.  Leaving any one of these relations behind
    # must make real legacy adoption fail closed as an unexpected catalog.
    await connection.execute("DROP VIEW IF EXISTS public.regulatory_validated_section_citations")
    await connection.execute(
        """
        DROP TABLE IF EXISTS
            public.regulatory_legal_version_provisions,
            public.regulatory_provisions,
            public.regulatory_legal_status_assertions,
            public.regulatory_legal_events,
            public.regulatory_legal_version_artifacts,
            public.regulatory_legal_versions,
            public.regulatory_evidence,
            public.regulatory_source_artifacts,
            public.regulatory_source_blobs,
            public.regulatory_family_imports,
            public.regulatory_instruments
        CASCADE
        """
    )
    # Reverse the additive v3 artifacts inside the surrounding rollback-only
    # transaction so the strict adopter sees the exact pre-ledger v1 catalog.
    for trigger_name in (
        "invalidate_retrieval_publication_on_chunk_insert",
        "invalidate_retrieval_publication_on_chunk_delete",
        "invalidate_retrieval_publication_on_chunk_update",
    ):
        await connection.execute(f"DROP TRIGGER IF EXISTS {trigger_name} ON public.document_chunks")
    await connection.execute("DROP FUNCTION IF EXISTS public.invalidate_retrieval_publication()")
    await connection.execute("DROP TABLE IF EXISTS public.document_retrieval_publications")
    await connection.execute("ALTER TABLE public.document_chunks DROP CONSTRAINT IF EXISTS document_chunks_document_fk")
    # PostgreSQL retains a dropped-column catalog slot after ``DROP COLUMN``.
    # The legacy verifier intentionally rejects that non-canonical shape, so
    # rebuild this otherwise-empty fixture table as the actual pre-ledger v1
    # relation instead of pretending a reverse migration produced one.
    await connection.execute("DROP TABLE public.document_sections CASCADE")
    await connection.execute(
        """
        CREATE TABLE public.document_sections (
            id pg_catalog.int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            doc_id pg_catalog.text NOT NULL,
            section_type pg_catalog.text NOT NULL,
            section_ref pg_catalog.text NOT NULL,
            heading pg_catalog.text DEFAULT '',
            start_char pg_catalog.int4 NOT NULL,
            end_char pg_catalog.int4 NOT NULL,
            content pg_catalog.text NOT NULL,
            content_hash pg_catalog.text NOT NULL,
            page_start pg_catalog.int4,
            page_end pg_catalog.int4,
            tsv pg_catalog.tsvector,
            CONSTRAINT document_sections_identity_uq
                UNIQUE (doc_id, section_type, section_ref, content_hash)
        )
        """
    )
    await connection.execute("CREATE INDEX idx_document_sections_doc_id ON public.document_sections (doc_id)")
    await connection.execute(
        "CREATE INDEX idx_document_sections_ref ON public.document_sections (section_type, section_ref)"
    )
    await connection.execute("CREATE INDEX idx_document_sections_tsv ON public.document_sections USING gin (tsv)")
    await connection.execute(
        """
        CREATE TRIGGER trg_document_sections_tsv
        BEFORE INSERT OR UPDATE ON public.document_sections
        FOR EACH ROW EXECUTE FUNCTION public.document_sections_tsv_trigger()
        """
    )


async def _downgrade_catalog_to_supported_legacy(connection) -> None:
    """Reproduce the final pre-ledger initializer shape without touching rows."""

    serial_columns = (
        ("document_chunks", "integer"),
        ("document_sections", "integer"),
        ("document_versions", "integer"),
        ("tool_call_traces", "bigint"),
    )
    for table, sequence_type in serial_columns:
        await connection.execute(f"ALTER TABLE public.{table} ALTER COLUMN id DROP IDENTITY IF EXISTS")
        await connection.execute(f"CREATE SEQUENCE public.{table}_id_seq AS {sequence_type} OWNED BY public.{table}.id")
        await connection.execute(
            f"ALTER TABLE public.{table} ALTER COLUMN id "
            f"SET DEFAULT pg_catalog.nextval('public.{table}_id_seq'::pg_catalog.regclass)"
        )

    await connection.execute(
        "ALTER TABLE public.document_chunks "
        "RENAME CONSTRAINT document_chunks_document_index_uq "
        "TO document_chunks_doc_id_chunk_index_key"
    )
    await connection.execute(
        "ALTER TABLE public.document_sections "
        "RENAME CONSTRAINT document_sections_identity_uq "
        "TO document_sections_doc_id_section_type_section_ref_content_hash_"
    )
    await connection.execute(
        "ALTER TABLE public.document_versions "
        "RENAME CONSTRAINT document_versions_document_version_uq "
        "TO document_versions_document_id_version_key"
    )

    await connection.execute(
        """
        CREATE OR REPLACE FUNCTION public.immutable_unaccent(pg_catalog.text)
        RETURNS pg_catalog.text AS $function$
            SELECT unaccent($1);
        $function$ LANGUAGE sql IMMUTABLE
        """
    )
    await connection.execute("ALTER FUNCTION public.immutable_unaccent(pg_catalog.text) RESET ALL")
    await connection.execute(
        """
        CREATE OR REPLACE FUNCTION public.documents_tsv_trigger() RETURNS trigger AS $function$
        BEGIN
            NEW.tsv :=
                to_tsvector('simple', immutable_unaccent(coalesce(NEW.title, '')))
                || to_tsvector('simple', immutable_unaccent(coalesce(NEW.markdown_content, '')))
                || to_tsvector('simple', immutable_unaccent(coalesce(NEW.category, '')));
            RETURN NEW;
        END;
        $function$ LANGUAGE plpgsql
        """
    )
    await connection.execute("ALTER FUNCTION public.documents_tsv_trigger() RESET ALL")
    await connection.execute(
        """
        CREATE OR REPLACE FUNCTION public.document_sections_tsv_trigger() RETURNS trigger AS $function$
        BEGIN
            NEW.tsv :=
                to_tsvector('simple', immutable_unaccent(coalesce(NEW.heading, '')))
                || to_tsvector('simple', immutable_unaccent(coalesce(NEW.content, '')));
            RETURN NEW;
        END;
        $function$ LANGUAGE plpgsql
        """
    )
    await connection.execute("ALTER FUNCTION public.document_sections_tsv_trigger() RESET ALL")
    await connection.execute(
        """
        CREATE OR REPLACE FUNCTION public.chunks_tsv_trigger() RETURNS trigger AS $function$
        BEGIN
            NEW.tsv := to_tsvector('simple', immutable_unaccent(coalesce(NEW.title, '')))
                    || to_tsvector('simple', immutable_unaccent(coalesce(NEW.chunk_text, '')));
            RETURN NEW;
        END;
        $function$ LANGUAGE plpgsql
        """
    )
    await connection.execute("ALTER FUNCTION public.chunks_tsv_trigger() RESET ALL")


async def _start_isolated_catalog(pg_pool):
    connection = await pg_pool.acquire()
    transaction = connection.transaction()
    await transaction.start()
    await _remove_managed_history(connection)
    await connection.execute(
        "CREATE ROLE bddk_test_schema_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS"
    )
    await connection.execute("GRANT bddk_test_schema_owner TO CURRENT_USER")
    database_grant = await connection.fetchval(
        "SELECT pg_catalog.format('GRANT CREATE ON DATABASE %I TO bddk_test_schema_owner', CURRENT_DATABASE())"
    )
    await connection.execute(database_grant)
    await connection.execute("ALTER SCHEMA public OWNER TO bddk_test_schema_owner")
    for table in (
        "decision_cache",
        "document_chunks",
        "document_sections",
        "document_versions",
        "documents",
        "sync_failures",
        "sync_metadata",
        "tool_call_traces",
    ):
        await connection.execute(f"ALTER TABLE public.{table} OWNER TO bddk_test_schema_owner")
    for sequence in (
        "document_chunks_id_seq",
        "document_sections_id_seq",
        "document_versions_id_seq",
        "tool_call_traces_id_seq",
    ):
        await connection.execute(f"ALTER SEQUENCE public.{sequence} OWNER TO bddk_test_schema_owner")
    for function in (
        "immutable_unaccent(pg_catalog.text)",
        "documents_tsv_trigger()",
        "document_sections_tsv_trigger()",
        "chunks_tsv_trigger()",
    ):
        await connection.execute(f"ALTER FUNCTION public.{function} OWNER TO bddk_test_schema_owner")
    await connection.execute("SET LOCAL ROLE bddk_test_schema_owner")
    return connection, transaction


async def _finish_isolated_catalog(pg_pool, connection, transaction) -> None:
    await connection.execute("RESET ROLE")
    await transaction.rollback()
    await pg_pool.release(connection)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_adoption_rejects_a_superuser_even_when_it_owns_the_exact_catalog(pg_pool) -> None:
    connection = await pg_pool.acquire()
    transaction = connection.transaction()
    await transaction.start()
    try:
        await _remove_managed_history(connection)

        with pytest.raises(LegacyAdoptionError, match="schema-owner-identity"):
            await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]

        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_meta.schema_migrations')") is None
    finally:
        await transaction.rollback()
        await pg_pool.release(connection)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_unmanaged_catalog_already_exactly_at_v1_is_adopted_without_normalization(pg_pool) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        state = await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]
        audit = await connection.fetchrow(
            """
            SELECT pre_normalization_fingerprint,
                   post_normalization_fingerprint,
                   normalizations
            FROM bddk_meta.legacy_schema_adoptions
            """
        )

        assert state.current
        assert audit["normalizations"] == []
        assert audit["pre_normalization_fingerprint"] == audit["post_normalization_fingerprint"]
        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_operator.operator_jobs')") is not None
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_supported_legacy_adoption_is_lossless_audited_and_idempotent(pg_pool) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        await connection.execute(
            """
            INSERT INTO public.documents (document_id, title, markdown_content, content_hash)
            VALUES ('legacy-proof-doc', 'Proof title', 'Proof body', 'proof-hash')
            """
        )
        await connection.execute(
            """
            INSERT INTO public.document_sections (
                id, doc_id, section_type, section_ref, start_char, end_char, content, content_hash
            ) VALUES (41, 'legacy-proof-doc', 'article', '1', 0, 10, 'Proof body', 'section-hash')
            """
        )
        await connection.execute(
            """
            INSERT INTO public.document_versions (
                id, document_id, version, content_hash, markdown_content, synced_at
            ) VALUES (42, 'legacy-proof-doc', 1, 'proof-hash', 'Proof body', 1.0)
            """
        )
        await connection.execute(
            """
            INSERT INTO public.document_chunks (
                id, doc_id, chunk_index, content_hash, chunk_text
            ) VALUES (44, 'legacy-proof-doc', 0, 'proof-hash', 'Proof body')
            """
        )
        before = await connection.fetchval(
            "SELECT pg_catalog.jsonb_build_object("
            "'document', (SELECT pg_catalog.to_jsonb(row_value) FROM public.documents AS row_value "
            "WHERE document_id = 'legacy-proof-doc'), "
            "'section', (SELECT pg_catalog.to_jsonb(row_value) - 'source_content_hash' "
            "FROM public.document_sections AS row_value "
            "WHERE id = 41), "
            "'version', (SELECT pg_catalog.to_jsonb(row_value) FROM public.document_versions AS row_value "
            "WHERE id = 42), "
            "'chunk', (SELECT pg_catalog.to_jsonb(row_value) FROM public.document_chunks AS row_value WHERE id = 44))"
        )

        await _downgrade_catalog_to_supported_legacy(connection)
        state = await migrate(  # type: ignore[arg-type]
            _PinnedPool(connection),
            adopt_legacy=True,
            allow_retrieval_publication_backfill=True,
        )
        second = await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]

        after = await connection.fetchval(
            "SELECT pg_catalog.jsonb_build_object("
            "'document', (SELECT pg_catalog.to_jsonb(row_value) FROM public.documents AS row_value "
            "WHERE document_id = 'legacy-proof-doc'), "
            "'section', (SELECT pg_catalog.to_jsonb(row_value) - 'source_content_hash' "
            "FROM public.document_sections AS row_value "
            "WHERE id = 41), "
            "'version', (SELECT pg_catalog.to_jsonb(row_value) FROM public.document_versions AS row_value "
            "WHERE id = 42), "
            "'chunk', (SELECT pg_catalog.to_jsonb(row_value) FROM public.document_chunks AS row_value WHERE id = 44))"
        )
        audit = await connection.fetchrow(
            """
            SELECT migration_version,
                   source_kind,
                   verifier_version,
                   target_checksum,
                   pre_normalization_fingerprint,
                   post_normalization_fingerprint,
                   normalizations,
                   adopted_by
            FROM bddk_meta.legacy_schema_adoptions
            """
        )
        audit_text = str(dict(audit))

        assert state.current and second.current
        assert state.current_version == LATEST_SCHEMA_VERSION
        assert before == after
        assert (
            await connection.fetchval("SELECT source_content_hash FROM public.document_sections WHERE id = 41")
            == "proof-hash"
        )
        assert len(audit["target_checksum"]) == 64
        assert len(audit["pre_normalization_fingerprint"]) == 64
        assert len(audit["post_normalization_fingerprint"]) == 64
        assert audit["pre_normalization_fingerprint"] != audit["post_normalization_fingerprint"]
        assert len(audit["normalizations"]) == 11
        assert "legacy-proof-doc" not in audit_text
        assert "Proof body" not in audit_text
        assert await connection.fetchval("SELECT pg_catalog.count(*) FROM bddk_meta.legacy_schema_adoptions") == 1

        # A recreated identity sequence must advance beyond pre-existing IDs.
        next_id = await connection.fetchval(
            "INSERT INTO public.document_chunks (doc_id, chunk_index, content_hash, chunk_text) "
            "VALUES ('legacy-proof-doc', 1, 'proof-hash', 'x') RETURNING id"
        )
        assert next_id > 44
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_default_migrate_refuses_even_an_exact_supported_unmanaged_schema(pg_pool) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        await _downgrade_catalog_to_supported_legacy(connection)

        with pytest.raises(MigrationError, match="rolled back"):
            await migrate(_PinnedPool(connection))  # type: ignore[arg-type]

        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_meta.schema_migrations')") is None
        assert await connection.fetchval(
            "SELECT attribute.attidentity = ''::pg_catalog.\"char\" "
            "FROM pg_catalog.pg_attribute AS attribute "
            "WHERE attribute.attrelid = 'public.document_chunks'::pg_catalog.regclass "
            "AND attribute.attname = 'id'"
        )
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)


@pytest.mark.postgres
@pytest.mark.asyncio
@pytest.mark.parametrize(
    "tamper",
    [
        "column",
        "function",
        "vector",
        "index",
        "trigger",
        "sequence",
        "constraint",
        "relation",
        "extra-relation",
        "table-acl",
        "sequence-acl",
        "rewrite-rule",
        "logical-publication",
        "owner",
    ],
)
async def test_adoption_refuses_tampered_or_incompatible_legacy_catalogs_without_partial_changes(
    pg_pool,
    tamper: str,
) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        await _downgrade_catalog_to_supported_legacy(connection)
        if tamper == "column":
            await connection.execute("ALTER TABLE public.documents ADD COLUMN unmanaged pg_catalog.text")
        elif tamper == "function":
            await connection.execute(
                """
                CREATE OR REPLACE FUNCTION public.documents_tsv_trigger() RETURNS trigger AS $function$
                BEGIN
                    NEW.tsv := NULL;
                    RETURN NEW;
                END;
                $function$ LANGUAGE plpgsql
                """
            )
        elif tamper == "vector":
            await connection.execute(
                "ALTER TABLE public.document_chunks "
                "ALTER COLUMN embedding TYPE public.vector(384) "
                "USING NULL::public.vector(384)"
            )
        elif tamper == "index":
            await connection.execute("DROP INDEX public.idx_documents_tsv")
        elif tamper == "trigger":
            await connection.execute("ALTER TABLE public.documents DISABLE TRIGGER trg_documents_tsv")
        elif tamper == "sequence":
            await connection.execute("ALTER SEQUENCE public.document_chunks_id_seq CACHE 2")
        elif tamper == "constraint":
            await connection.execute("ALTER TABLE public.sync_metadata DROP CONSTRAINT sync_metadata_pkey")
        elif tamper == "relation":
            await connection.execute("ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY")
        elif tamper == "extra-relation":
            await connection.execute("CREATE TABLE public.unmanaged_relation (id pg_catalog.int4)")
        elif tamper == "table-acl":
            await connection.execute("GRANT SELECT ON public.documents TO PUBLIC")
        elif tamper == "sequence-acl":
            await connection.execute("GRANT USAGE ON SEQUENCE public.document_chunks_id_seq TO PUBLIC")
        elif tamper == "rewrite-rule":
            await connection.execute(
                "CREATE RULE unmanaged_documents_update AS ON UPDATE TO public.documents DO ALSO NOTHING"
            )
        elif tamper == "logical-publication":
            await connection.execute("CREATE PUBLICATION unmanaged_publication FOR TABLE public.documents")
        else:
            await connection.execute("RESET ROLE")
            await connection.execute("CREATE ROLE incompatible_legacy_owner")
            await connection.execute("ALTER TABLE public.documents OWNER TO incompatible_legacy_owner")
            await connection.execute("SET LOCAL ROLE bddk_test_schema_owner")

        with pytest.raises(LegacyAdoptionError, match="No corpus rows were changed"):
            await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]

        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_meta.schema_migrations')") is None
        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_operator.operator_jobs')") is None
        assert await connection.fetchval(
            "SELECT attribute.attidentity = ''::pg_catalog.\"char\" "
            "FROM pg_catalog.pg_attribute AS attribute "
            "WHERE attribute.attrelid = 'public.document_chunks'::pg_catalog.regclass "
            "AND attribute.attname = 'id'"
        )
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_adoption_refuses_misplaced_extensions_before_any_catalog_normalization(pg_pool) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        await _downgrade_catalog_to_supported_legacy(connection)
        await connection.execute("RESET ROLE")
        await connection.execute("CREATE SCHEMA misplaced_extensions")
        await connection.execute("ALTER EXTENSION unaccent SET SCHEMA misplaced_extensions")
        await connection.execute("SET LOCAL ROLE bddk_test_schema_owner")

        with pytest.raises(MigrationPrerequisiteError, match="public schema"):
            await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]

        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_meta.schema_migrations')") is None
        assert await connection.fetchval(
            "SELECT attribute.attidentity = ''::pg_catalog.\"char\" "
            "FROM pg_catalog.pg_attribute AS attribute "
            "WHERE attribute.attrelid = 'public.document_chunks'::pg_catalog.regclass "
            "AND attribute.attname = 'id'"
        )
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_failure_after_normalization_rolls_back_every_metadata_change(pg_pool) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        await _downgrade_catalog_to_supported_legacy(connection)

        from bddk_mcp.migrations.legacy import normalize_legacy_v1 as real_normalize

        async def normalize_then_fail(active_connection, inspection) -> None:
            await real_normalize(active_connection, inspection)
            raise asyncpg.PostgresError("deliberate private driver detail")

        with patch("bddk_mcp.migrations.runner.normalize_legacy_v1", new=normalize_then_fail):
            with pytest.raises(MigrationError, match="rolled back") as exc_info:
                await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]

        assert "deliberate private driver detail" not in str(exc_info.value)
        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_meta.schema_migrations')") is None
        assert await connection.fetchval(
            "SELECT attribute.attidentity = ''::pg_catalog.\"char\" "
            "FROM pg_catalog.pg_attribute AS attribute "
            "WHERE attribute.attrelid = 'public.document_chunks'::pg_catalog.regclass "
            "AND attribute.attname = 'id'"
        )
        assert await connection.fetchval(
            "SELECT pg_catalog.to_regclass('public.document_chunks_doc_id_chunk_index_key') IS NOT NULL"
        )
        assert await connection.fetchval(
            "SELECT function_record.proconfig IS NULL "
            "FROM pg_catalog.pg_proc AS function_record "
            "WHERE function_record.oid = "
            "'public.immutable_unaccent(pg_catalog.text)'::pg_catalog.regprocedure"
        )
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)


@pytest.mark.postgres
@pytest.mark.asyncio
async def test_adoption_flag_rejects_an_empty_database_and_points_to_normal_migration(pg_pool) -> None:
    connection, transaction = await _start_isolated_catalog(pg_pool)
    try:
        await connection.execute(
            """
            DROP TABLE
                public.document_chunks,
                public.decision_cache,
                public.sync_failures,
                public.sync_metadata,
                public.tool_call_traces,
                public.document_versions,
                public.document_sections,
                public.documents
            CASCADE
            """
        )

        with pytest.raises(LegacyAdoptionError, match="blue-green data-only procedure"):
            await migrate(_PinnedPool(connection), adopt_legacy=True)  # type: ignore[arg-type]

        assert await connection.fetchval("SELECT pg_catalog.to_regclass('bddk_meta.schema_migrations')") is None
    finally:
        await _finish_isolated_catalog(pg_pool, connection, transaction)
