"""Migration 0001: canonical public document and retrieval schema."""

from bddk_mcp.migrations.model import Migration

V0001_CORE = Migration(
    version=1,
    name="core_document_retrieval_schema",
    statements=(
        """
        CREATE FUNCTION public.immutable_unaccent(pg_catalog.text)
        RETURNS pg_catalog.text
        LANGUAGE sql
        IMMUTABLE
        PARALLEL SAFE
        SET search_path = pg_catalog, public
        AS $function$
            SELECT public.unaccent($1)
        $function$
        """,
        """
        CREATE TABLE public.documents (
            document_id pg_catalog.text PRIMARY KEY,
            title pg_catalog.text NOT NULL,
            category pg_catalog.text DEFAULT '',
            decision_date pg_catalog.text DEFAULT '',
            decision_number pg_catalog.text DEFAULT '',
            source_url pg_catalog.text DEFAULT '',
            pdf_blob pg_catalog.bytea,
            markdown_content pg_catalog.text DEFAULT '',
            content_hash pg_catalog.text DEFAULT '',
            downloaded_at pg_catalog.float8,
            extracted_at pg_catalog.float8,
            extraction_method pg_catalog.text DEFAULT 'markitdown',
            total_pages pg_catalog.int4 DEFAULT 1,
            file_size pg_catalog.int4 DEFAULT 0,
            tsv pg_catalog.tsvector
        )
        """,
        "CREATE INDEX idx_documents_category ON public.documents (category)",
        "CREATE INDEX idx_documents_date ON public.documents (decision_date)",
        "CREATE INDEX idx_documents_tsv ON public.documents USING gin (tsv)",
        """
        CREATE TABLE public.document_sections (
            id pg_catalog.int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            doc_id pg_catalog.text NOT NULL,
            section_type pg_catalog.text NOT NULL,
            section_ref pg_catalog.text NOT NULL,
            heading pg_catalog.text DEFAULT '',
            start_char pg_catalog.int4 NOT NULL,
            end_char pg_catalog.int4 NOT NULL,
            content pg_catalog.text NOT NULL,
            content_hash pg_catalog.text NOT NULL,
            page_start pg_catalog.int4,
            page_end pg_catalog.int4,
            tsv pg_catalog.tsvector,
            CONSTRAINT document_sections_identity_uq
                UNIQUE (doc_id, section_type, section_ref, content_hash)
        )
        """,
        "CREATE INDEX idx_document_sections_doc_id ON public.document_sections (doc_id)",
        """
        CREATE INDEX idx_document_sections_ref
        ON public.document_sections (section_type, section_ref)
        """,
        "CREATE INDEX idx_document_sections_tsv ON public.document_sections USING gin (tsv)",
        """
        CREATE FUNCTION public.documents_tsv_trigger()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $function$
        BEGIN
            NEW.tsv :=
                pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.title, ''))
                )
                || pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.markdown_content, ''))
                )
                || pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.category, ''))
                );
            RETURN NEW;
        END
        $function$
        """,
        """
        CREATE TRIGGER trg_documents_tsv
        BEFORE INSERT OR UPDATE ON public.documents
        FOR EACH ROW EXECUTE FUNCTION public.documents_tsv_trigger()
        """,
        """
        CREATE FUNCTION public.document_sections_tsv_trigger()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $function$
        BEGIN
            NEW.tsv :=
                pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.heading, ''))
                )
                || pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.content, ''))
                );
            RETURN NEW;
        END
        $function$
        """,
        """
        CREATE TRIGGER trg_document_sections_tsv
        BEFORE INSERT OR UPDATE ON public.document_sections
        FOR EACH ROW EXECUTE FUNCTION public.document_sections_tsv_trigger()
        """,
        """
        CREATE TABLE public.document_versions (
            id pg_catalog.int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id pg_catalog.text NOT NULL,
            version pg_catalog.int4 NOT NULL DEFAULT 1,
            content_hash pg_catalog.text NOT NULL,
            markdown_content pg_catalog.text DEFAULT '',
            synced_at pg_catalog.float8 NOT NULL,
            CONSTRAINT document_versions_document_version_uq UNIQUE (document_id, version)
        )
        """,
        "CREATE INDEX idx_versions_doc_id ON public.document_versions (document_id)",
        """
        CREATE TABLE public.tool_call_traces (
            id pg_catalog.int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at pg_catalog.timestamptz DEFAULT pg_catalog.now(),
            tool_name pg_catalog.text NOT NULL,
            args_hash pg_catalog.text NOT NULL,
            args_summary pg_catalog.jsonb,
            latency_ms pg_catalog.int4,
            result_count pg_catalog.int4,
            doc_ids pg_catalog.text[],
            quality_labels pg_catalog.jsonb,
            relevance_stats pg_catalog.jsonb,
            model_id pg_catalog.text,
            session_id pg_catalog.text
        )
        """,
        """
        CREATE INDEX idx_tool_call_traces_created_at
        ON public.tool_call_traces (created_at DESC)
        """,
        "CREATE INDEX idx_tool_call_traces_tool_name ON public.tool_call_traces (tool_name)",
        "CREATE INDEX idx_tool_call_traces_doc_ids ON public.tool_call_traces USING gin (doc_ids)",
        """
        CREATE TABLE public.sync_metadata (
            document_id pg_catalog.text PRIMARY KEY,
            etag pg_catalog.text DEFAULT '',
            last_modified pg_catalog.text DEFAULT '',
            last_sync_at pg_catalog.float8,
            sync_count pg_catalog.int4 DEFAULT 0
        )
        """,
        """
        CREATE TABLE public.sync_failures (
            document_id pg_catalog.text PRIMARY KEY,
            error pg_catalog.text NOT NULL,
            error_category pg_catalog.text NOT NULL DEFAULT 'unknown',
            source_url pg_catalog.text DEFAULT '',
            retryable pg_catalog.bool DEFAULT true,
            attempts pg_catalog.int4 DEFAULT 1,
            first_failed_at pg_catalog.float8,
            last_failed_at pg_catalog.float8
        )
        """,
        """
        CREATE TABLE public.decision_cache (
            document_id pg_catalog.text PRIMARY KEY,
            title pg_catalog.text NOT NULL DEFAULT '',
            content pg_catalog.text DEFAULT '',
            decision_date pg_catalog.text DEFAULT '',
            decision_number pg_catalog.text DEFAULT '',
            category pg_catalog.text DEFAULT '',
            source_url pg_catalog.text DEFAULT '',
            cached_at pg_catalog.float8 NOT NULL
        )
        """,
        "CREATE INDEX idx_decision_cache_category ON public.decision_cache (category)",
        """
        CREATE TABLE public.document_chunks (
            id pg_catalog.int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            doc_id pg_catalog.text NOT NULL,
            chunk_index pg_catalog.int4 NOT NULL,
            title pg_catalog.text DEFAULT '',
            category pg_catalog.text DEFAULT '',
            decision_date pg_catalog.text DEFAULT '',
            decision_number pg_catalog.text DEFAULT '',
            source_url pg_catalog.text DEFAULT '',
            total_chunks pg_catalog.int4 DEFAULT 1,
            total_pages pg_catalog.int4 DEFAULT 1,
            content_hash pg_catalog.text DEFAULT '',
            chunk_start_char pg_catalog.int4,
            chunk_end_char pg_catalog.int4,
            section_type pg_catalog.text DEFAULT '',
            section_ref pg_catalog.text DEFAULT '',
            section_start_char pg_catalog.int4,
            section_end_char pg_catalog.int4,
            section_content_hash pg_catalog.text DEFAULT '',
            chunk_text pg_catalog.text NOT NULL,
            embedding public.vector(768),
            tsv pg_catalog.tsvector,
            CONSTRAINT document_chunks_document_index_uq UNIQUE (doc_id, chunk_index)
        )
        """,
        "CREATE INDEX idx_chunks_doc_id ON public.document_chunks (doc_id)",
        "CREATE INDEX idx_chunks_tsv ON public.document_chunks USING gin (tsv)",
        """
        CREATE INDEX idx_chunks_section_ref
        ON public.document_chunks (section_type, section_ref)
        """,
        """
        CREATE FUNCTION public.chunks_tsv_trigger()
        RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public
        AS $function$
        BEGIN
            NEW.tsv :=
                pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.title, ''))
                )
                || pg_catalog.to_tsvector(
                    'simple'::pg_catalog.regconfig,
                    public.immutable_unaccent(COALESCE(NEW.chunk_text, ''))
                );
            RETURN NEW;
        END
        $function$
        """,
        """
        CREATE TRIGGER chunks_tsv_update
        BEFORE INSERT OR UPDATE ON public.document_chunks
        FOR EACH ROW EXECUTE FUNCTION public.chunks_tsv_trigger()
        """,
        """
        CREATE INDEX idx_chunks_embedding_hnsw
        ON public.document_chunks USING hnsw (embedding public.vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """,
    ),
)
